-- 插入50个对话剧本
INSERT INTO conversation_scripts (name, description, category, relationship, time_of_day, estimated_duration, difficulty, tags, flow, version, is_active, usage_count, success_rate, average_rating, total_ratings, created_at, updated_at) VALUES
  (
    '早安问候 1',
    '简单的早安问候对话',
    'casual',
    'friends',
    'morning',
    5,
    'easy',
    ARRAY['问候', '日常', '简单'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":3,"variations":["嗨！近来好吗？","嗨！这些天好吗？"]},{"role":"responder","message":"周末有什么计划？","delay_seconds":3,"variations":["周末有什么计划？","周末有什么计划？","周末有什么计划？"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":4,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":3,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":3,"variations":["近来看了什么好电影？","这些天看了什么好电影？","这段时间看了什么好电影？"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":5,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    27,
    71,
    4.505241851641179,
    8,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '周末计划讨论 1',
    '讨论周末计划的对话',
    'casual',
    'friends',
    'afternoon',
    8,
    'easy',
    ARRAY['周末', '计划', '休闲'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":5,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":3,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"周末有什么计划？","delay_seconds":5,"variations":["周末有什么计划？","周末有什么计划？","周末有什么计划？"]},{"role":"responder","message":"今天天气不错","delay_seconds":4,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"initiator","message":"很高兴和你聊天","delay_seconds":5,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    71,
    88,
    3.583577484480341,
    16,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '工作项目讨论 1',
    '同事之间讨论工作项目的对话',
    'business',
    'colleagues',
    'any',
    10,
    'medium',
    ARRAY['工作', '项目', '讨论'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":3,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"关于那个项目，你有什么想法？","delay_seconds":4,"variations":["关于那个项目，你有什么想法？","关于那个项目，你有什么想法？","关于那个项目，你有什么想法？"]},{"role":"initiator","message":"这个任务什么时候能完成？","delay_seconds":4,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"responder","message":"会议安排在明天可以吗？","delay_seconds":4,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"initiator","message":"保持联系！","delay_seconds":2,"variations":["保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    82,
    95,
    3.5829099460531735,
    0,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '兴趣爱好分享 1',
    '分享兴趣爱好的对话',
    'hobby',
    'acquaintances',
    'evening',
    12,
    'easy',
    ARRAY['兴趣', '爱好', '分享'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":4,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"你平时有什么兴趣爱好？","delay_seconds":2,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"responder","message":"很高兴和你聊天","delay_seconds":3,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    30,
    77,
    3.6338973227579077,
    43,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '健身话题讨论 1',
    '讨论健身和健康的对话',
    'hobby',
    'friends',
    'any',
    10,
    'medium',
    ARRAY['健身', '健康', '运动'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":3,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":2,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":3,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":5,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    87,
    81,
    4.719969924841972,
    35,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '美食推荐 1',
    '推荐美食和餐厅的对话',
    'casual',
    'friends',
    'any',
    9,
    'easy',
    ARRAY['美食', '餐厅', '推荐'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":2,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":2,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"responder","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":2,"variations":["近来看了什么好电影？","这些天看了什么好电影？","这段时间看了什么好电影？"]},{"role":"responder","message":"周末有什么计划？","delay_seconds":4,"variations":["周末有什么计划？","周末有什么计划？","周末有什么计划？"]},{"role":"initiator","message":"再见，祝你愉快","delay_seconds":2,"variations":["再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    2,
    70,
    3.563037108547305,
    27,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '旅行计划 1',
    '讨论旅行计划的对话',
    'hobby',
    'friends',
    'any',
    12,
    'medium',
    ARRAY['旅行', '计划', '假期'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":4,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":2,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"initiator","message":"你平时有什么兴趣爱好？","delay_seconds":4,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":5,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"你平时有什么兴趣爱好？","delay_seconds":3,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":3,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    35,
    95,
    4.361526265924448,
    14,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '电影讨论 1',
    '讨论电影和影评的对话',
    'hobby',
    'acquaintances',
    'evening',
    11,
    'easy',
    ARRAY['电影', '娱乐', '讨论'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":5,"variations":["嗨，近来如何？","嗨，这些天好吗？","嗨，这段时间怎样？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":2,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"最近在玩什么游戏？","delay_seconds":4,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"responder","message":"好的，下次再聊","delay_seconds":4,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    97,
    86,
    4.443698019240327,
    28,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '技术问题讨论 1',
    '讨论技术问题和解决方案的对话',
    'business',
    'colleagues',
    'any',
    15,
    'hard',
    ARRAY['技术', '问题', '解决方案'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？","哈喽啊！这段时间如何？"]},{"role":"responder","message":"这个任务什么时候能完成？","delay_seconds":3,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"initiator","message":"我们需要讨论一下进度","delay_seconds":3,"variations":["我们需要讨论一下进度","我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"responder","message":"会议安排在明天可以吗？","delay_seconds":2,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"initiator","message":"我们需要讨论一下进度","delay_seconds":3,"variations":["我们需要讨论一下进度","我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"responder","message":"我们需要讨论一下进度","delay_seconds":3,"variations":["我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":3,"variations":["好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    19,
    94,
    3.502425055220023,
    30,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '天气话题 1',
    '讨论天气和季节变化的对话',
    'casual',
    'acquaintances',
    'any',
    6,
    'easy',
    ARRAY['天气', '季节', '日常'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？"]},{"role":"responder","message":"今天天气不错","delay_seconds":4,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"initiator","message":"周末有什么计划？","delay_seconds":3,"variations":["周末有什么计划？","周末有什么计划？","周末有什么计划？"]},{"role":"responder","message":"保持联系！","delay_seconds":5,"variations":["保持联系！","保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    68,
    89,
    4.612086724893745,
    41,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '早安问候 2',
    '简单的早安问候对话',
    'casual',
    'friends',
    'morning',
    5,
    'easy',
    ARRAY['问候', '日常', '简单'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":2,"variations":["嗨！近来好吗？","嗨！这些天好吗？","嗨！这段时间好吗？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":4,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":5,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"responder","message":"今天天气不错","delay_seconds":2,"variations":["今天天气不错","今天天气不错"]},{"role":"initiator","message":"保持联系！","delay_seconds":3,"variations":["保持联系！","保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    22,
    75,
    4.083600484317551,
    16,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '周末计划讨论 2',
    '讨论周末计划的对话',
    'casual',
    'friends',
    'afternoon',
    8,
    'easy',
    ARRAY['周末', '计划', '休闲'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":3,"variations":["嗨！近来如何？","你好啊！这些天好吗？","哈喽！这段时间怎样？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":5,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":4,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":3,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    19,
    97,
    4.132277085111796,
    32,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '工作项目讨论 2',
    '同事之间讨论工作项目的对话',
    'business',
    'colleagues',
    'any',
    10,
    'medium',
    ARRAY['工作', '项目', '讨论'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？","哈喽！这段时间怎样？"]},{"role":"responder","message":"会议安排在明天可以吗？","delay_seconds":2,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"initiator","message":"会议安排在明天可以吗？","delay_seconds":2,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"responder","message":"我们需要讨论一下进度","delay_seconds":2,"variations":["我们需要讨论一下进度","我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":5,"variations":["好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    44,
    98,
    4.455886925074278,
    35,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '兴趣爱好分享 2',
    '分享兴趣爱好的对话',
    'hobby',
    'acquaintances',
    'evening',
    12,
    'easy',
    ARRAY['兴趣', '爱好', '分享'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":4,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":4,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":4,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"保持联系！","delay_seconds":2,"variations":["保持联系！","保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    94,
    75,
    3.782715905101883,
    6,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '健身话题讨论 2',
    '讨论健身和健康的对话',
    'hobby',
    'friends',
    'any',
    10,
    'medium',
    ARRAY['健身', '健康', '运动'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":2,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":3,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":5,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":4,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":5,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    71,
    89,
    4.435766669844982,
    9,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '美食推荐 2',
    '推荐美食和餐厅的对话',
    'casual',
    'friends',
    'any',
    9,
    'easy',
    ARRAY['美食', '餐厅', '推荐'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":5,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？","哈喽啊！这段时间如何？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":5,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":2,"variations":["近来看了什么好电影？","这些天看了什么好电影？","这段时间看了什么好电影？"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":2,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    44,
    79,
    3.627494908737567,
    33,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '旅行计划 2',
    '讨论旅行计划的对话',
    'hobby',
    'friends',
    'any',
    12,
    'medium',
    ARRAY['旅行', '计划', '假期'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":5,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"你平时有什么兴趣爱好？","delay_seconds":5,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"responder","message":"保持联系！","delay_seconds":5,"variations":["保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    62,
    74,
    3.893726963937597,
    47,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '电影讨论 2',
    '讨论电影和影评的对话',
    'hobby',
    'acquaintances',
    'evening',
    11,
    'easy',
    ARRAY['电影', '娱乐', '讨论'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":2,"variations":["嗨！近来好吗？","嗨！这些天好吗？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":3,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":5,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":3,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    7,
    89,
    3.6378901542818993,
    40,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '技术问题讨论 2',
    '讨论技术问题和解决方案的对话',
    'business',
    'colleagues',
    'any',
    15,
    'hard',
    ARRAY['技术', '问题', '解决方案'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":2,"variations":["嗨！近来好吗？","嗨！这些天好吗？","嗨！这段时间好吗？"]},{"role":"responder","message":"这个任务什么时候能完成？","delay_seconds":2,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"initiator","message":"这个任务什么时候能完成？","delay_seconds":2,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"responder","message":"我们需要讨论一下进度","delay_seconds":4,"variations":["我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"initiator","message":"会议安排在明天可以吗？","delay_seconds":3,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"responder","message":"很高兴和你聊天","delay_seconds":3,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    49,
    91,
    3.614979835395317,
    15,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '天气话题 2',
    '讨论天气和季节变化的对话',
    'casual',
    'acquaintances',
    'any',
    6,
    'easy',
    ARRAY['天气', '季节', '日常'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":4,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":4,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"responder","message":"今天天气不错","delay_seconds":5,"variations":["今天天气不错","今天天气不错"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":2,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"responder","message":"好的，下次再聊","delay_seconds":2,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    7,
    79,
    4.6100799418417235,
    1,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '早安问候 3',
    '简单的早安问候对话',
    'casual',
    'friends',
    'morning',
    5,
    'easy',
    ARRAY['问候', '日常', '简单'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":5,"variations":["嗨！近来好吗？","嗨！这些天好吗？","嗨！这段时间好吗？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":5,"variations":["近来看了什么好电影？","这些天看了什么好电影？","这段时间看了什么好电影？"]},{"role":"initiator","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"responder","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":3,"variations":["近来看了什么好电影？","这些天看了什么好电影？","这段时间看了什么好电影？"]},{"role":"responder","message":"很高兴和你聊天","delay_seconds":2,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    86,
    95,
    4.4218758791621084,
    33,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '周末计划讨论 3',
    '讨论周末计划的对话',
    'casual',
    'friends',
    'afternoon',
    8,
    'easy',
    ARRAY['周末', '计划', '休闲'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？","哈喽啊！这段时间如何？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":4,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"周末有什么计划？","delay_seconds":2,"variations":["周末有什么计划？","周末有什么计划？","周末有什么计划？"]},{"role":"responder","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":4,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":3,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"保持联系！","delay_seconds":5,"variations":["保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    80,
    70,
    4.895207014701067,
    22,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '工作项目讨论 3',
    '同事之间讨论工作项目的对话',
    'business',
    'colleagues',
    'any',
    10,
    'medium',
    ARRAY['工作', '项目', '讨论'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？","哈喽啊！这段时间如何？"]},{"role":"responder","message":"关于那个项目，你有什么想法？","delay_seconds":3,"variations":["关于那个项目，你有什么想法？","关于那个项目，你有什么想法？","关于那个项目，你有什么想法？"]},{"role":"initiator","message":"这个任务什么时候能完成？","delay_seconds":4,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"responder","message":"好的，下次再聊","delay_seconds":3,"variations":["好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    60,
    99,
    4.92500875849345,
    11,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '兴趣爱好分享 3',
    '分享兴趣爱好的对话',
    'hobby',
    'acquaintances',
    'evening',
    12,
    'easy',
    ARRAY['兴趣', '爱好', '分享'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？","哈喽！这段时间怎样？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":4,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":5,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":3,"variations":["有什么好书推荐吗？","有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"再见，祝你愉快","delay_seconds":5,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    90,
    89,
    4.412400223070577,
    37,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '健身话题讨论 3',
    '讨论健身和健康的对话',
    'hobby',
    'friends',
    'any',
    10,
    'medium',
    ARRAY['健身', '健康', '运动'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":4,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":5,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":2,"variations":["有什么好书推荐吗？","有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":5,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":4,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":2,"variations":["再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    84,
    77,
    3.7798897944658445,
    3,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '美食推荐 3',
    '推荐美食和餐厅的对话',
    'casual',
    'friends',
    'any',
    9,
    'easy',
    ARRAY['美食', '餐厅', '推荐'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":2,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":2,"variations":["近来看了什么好电影？","这些天看了什么好电影？","这段时间看了什么好电影？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":5,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":5,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    34,
    95,
    4.172550135467215,
    42,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '旅行计划 3',
    '讨论旅行计划的对话',
    'hobby',
    'friends',
    'any',
    12,
    'medium',
    ARRAY['旅行', '计划', '假期'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":3,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":2,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？","这段时间在玩什么游戏？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":3,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":2,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":4,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":5,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"很高兴和你聊天","delay_seconds":2,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    59,
    73,
    4.648071692996242,
    1,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '电影讨论 3',
    '讨论电影和影评的对话',
    'hobby',
    'acquaintances',
    'evening',
    11,
    'easy',
    ARRAY['电影', '娱乐', '讨论'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？","哈喽啊！这段时间如何？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":4,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":4,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"很高兴和你聊天","delay_seconds":3,"variations":["很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    13,
    90,
    4.81655900901942,
    9,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '技术问题讨论 3',
    '讨论技术问题和解决方案的对话',
    'business',
    'colleagues',
    'any',
    15,
    'hard',
    ARRAY['技术', '问题', '解决方案'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？"]},{"role":"responder","message":"我们需要讨论一下进度","delay_seconds":3,"variations":["我们需要讨论一下进度","我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"initiator","message":"关于那个项目，你有什么想法？","delay_seconds":5,"variations":["关于那个项目，你有什么想法？","关于那个项目，你有什么想法？","关于那个项目，你有什么想法？"]},{"role":"responder","message":"关于那个项目，你有什么想法？","delay_seconds":2,"variations":["关于那个项目，你有什么想法？","关于那个项目，你有什么想法？","关于那个项目，你有什么想法？"]},{"role":"initiator","message":"保持联系！","delay_seconds":2,"variations":["保持联系！","保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    32,
    76,
    4.728290567305434,
    28,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '天气话题 3',
    '讨论天气和季节变化的对话',
    'casual',
    'acquaintances',
    'any',
    6,
    'easy',
    ARRAY['天气', '季节', '日常'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":2,"variations":["嗨，近来如何？","嗨，这些天好吗？","嗨，这段时间怎样？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"周末有什么计划？","delay_seconds":5,"variations":["周末有什么计划？","周末有什么计划？"]},{"role":"responder","message":"保持联系！","delay_seconds":4,"variations":["保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    74,
    99,
    4.261657018663151,
    44,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '早安问候 4',
    '简单的早安问候对话',
    'casual',
    'friends',
    'morning',
    5,
    'easy',
    ARRAY['问候', '日常', '简单'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":4,"variations":["嗨，近来如何？","嗨，这些天好吗？","嗨，这段时间怎样？"]},{"role":"responder","message":"周末有什么计划？","delay_seconds":5,"variations":["周末有什么计划？","周末有什么计划？"]},{"role":"initiator","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":4,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"很高兴和你聊天","delay_seconds":3,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    87,
    72,
    3.6633238078389225,
    24,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '周末计划讨论 4',
    '讨论周末计划的对话',
    'casual',
    'friends',
    'afternoon',
    8,
    'easy',
    ARRAY['周末', '计划', '休闲'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":3,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":5,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"responder","message":"好的，下次再聊","delay_seconds":4,"variations":["好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    71,
    84,
    4.682740451614199,
    32,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '工作项目讨论 4',
    '同事之间讨论工作项目的对话',
    'business',
    'colleagues',
    'any',
    10,
    'medium',
    ARRAY['工作', '项目', '讨论'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"这个任务什么时候能完成？","delay_seconds":2,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"initiator","message":"会议安排在明天可以吗？","delay_seconds":3,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"responder","message":"这个任务什么时候能完成？","delay_seconds":4,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"initiator","message":"关于那个项目，你有什么想法？","delay_seconds":4,"variations":["关于那个项目，你有什么想法？","关于那个项目，你有什么想法？","关于那个项目，你有什么想法？"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":3,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    88,
    91,
    4.707190859340285,
    48,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '兴趣爱好分享 4',
    '分享兴趣爱好的对话',
    'hobby',
    'acquaintances',
    'evening',
    12,
    'easy',
    ARRAY['兴趣', '爱好', '分享'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？","哈喽！这段时间怎样？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":4,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"initiator","message":"你平时有什么兴趣爱好？","delay_seconds":4,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":3,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？","这段时间在玩什么游戏？"]},{"role":"initiator","message":"最近在玩什么游戏？","delay_seconds":2,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"responder","message":"很高兴和你聊天","delay_seconds":3,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    49,
    72,
    3.900563808408859,
    44,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '健身话题讨论 4',
    '讨论健身和健康的对话',
    'hobby',
    'friends',
    'any',
    10,
    'medium',
    ARRAY['健身', '健康', '运动'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":4,"variations":["嗨！近来如何？","你好啊！这些天好吗？","哈喽！这段时间怎样？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":4,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":2,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":2,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"最近在玩什么游戏？","delay_seconds":5,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":4,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":5,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    19,
    82,
    4.515304618812555,
    28,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '美食推荐 4',
    '推荐美食和餐厅的对话',
    'casual',
    'friends',
    'any',
    9,
    'easy',
    ARRAY['美食', '餐厅', '推荐'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":4,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"最近工作忙吗？","delay_seconds":4,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":3,"variations":["近来看了什么好电影？","这些天看了什么好电影？","这段时间看了什么好电影？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":4,"variations":["今天天气不错","今天天气不错"]},{"role":"responder","message":"保持联系！","delay_seconds":3,"variations":["保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    17,
    83,
    3.5061251582971873,
    5,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '旅行计划 4',
    '讨论旅行计划的对话',
    'hobby',
    'friends',
    'any',
    12,
    'medium',
    ARRAY['旅行', '计划', '假期'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":4,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":2,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":2,"variations":["有什么好书推荐吗？","有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":3,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"最近在玩什么游戏？","delay_seconds":3,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":3,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"保持联系！","delay_seconds":5,"variations":["保持联系！","保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    45,
    78,
    4.572968995101487,
    47,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '电影讨论 4',
    '讨论电影和影评的对话',
    'hobby',
    'acquaintances',
    'evening',
    11,
    'easy',
    ARRAY['电影', '娱乐', '讨论'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":5,"variations":["嗨，近来如何？","嗨，这些天好吗？","嗨，这段时间怎样？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":3,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":4,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"保持联系！","delay_seconds":2,"variations":["保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    36,
    72,
    4.060965967171634,
    19,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '技术问题讨论 4',
    '讨论技术问题和解决方案的对话',
    'business',
    'colleagues',
    'any',
    15,
    'hard',
    ARRAY['技术', '问题', '解决方案'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":3,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"这个任务什么时候能完成？","delay_seconds":5,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"initiator","message":"我们需要讨论一下进度","delay_seconds":2,"variations":["我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"responder","message":"这个任务什么时候能完成？","delay_seconds":4,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"initiator","message":"很高兴和你聊天","delay_seconds":2,"variations":["很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    1,
    82,
    3.6208418253517562,
    21,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '天气话题 4',
    '讨论天气和季节变化的对话',
    'casual',
    'acquaintances',
    'any',
    6,
    'easy',
    ARRAY['天气', '季节', '日常'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":5,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"周末有什么计划？","delay_seconds":5,"variations":["周末有什么计划？","周末有什么计划？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":4,"variations":["今天天气不错","今天天气不错"]},{"role":"responder","message":"周末有什么计划？","delay_seconds":4,"variations":["周末有什么计划？","周末有什么计划？"]},{"role":"initiator","message":"周末有什么计划？","delay_seconds":4,"variations":["周末有什么计划？","周末有什么计划？","周末有什么计划？"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":5,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"保持联系！","delay_seconds":4,"variations":["保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    27,
    75,
    4.974141817588708,
    2,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '早安问候 5',
    '简单的早安问候对话',
    'casual',
    'friends',
    'morning',
    5,
    'easy',
    ARRAY['问候', '日常', '简单'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":2,"variations":["嗨！近来好吗？","嗨！这些天好吗？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":5,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"responder","message":"最近看了什么好电影？","delay_seconds":5,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"initiator","message":"很高兴和你聊天","delay_seconds":2,"variations":["很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    8,
    79,
    4.463348447305032,
    47,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '周末计划讨论 5',
    '讨论周末计划的对话',
    'casual',
    'friends',
    'afternoon',
    8,
    'easy',
    ARRAY['周末', '计划', '休闲'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":5,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"initiator","message":"最近工作忙吗？","delay_seconds":4,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"responder","message":"今天天气不错","delay_seconds":2,"variations":["今天天气不错","今天天气不错"]},{"role":"initiator","message":"最近工作忙吗？","delay_seconds":2,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"responder","message":"今天天气不错","delay_seconds":5,"variations":["今天天气不错","今天天气不错"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":5,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    22,
    97,
    3.6131437602769862,
    10,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '工作项目讨论 5',
    '同事之间讨论工作项目的对话',
    'business',
    'colleagues',
    'any',
    10,
    'medium',
    ARRAY['工作', '项目', '讨论'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":3,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"会议安排在明天可以吗？","delay_seconds":2,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"initiator","message":"会议安排在明天可以吗？","delay_seconds":5,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"responder","message":"这个任务什么时候能完成？","delay_seconds":4,"variations":["这个任务什么时候能完成？","这个任务什么时候能完成？","这个任务什么时候能完成？"]},{"role":"initiator","message":"关于那个项目，你有什么想法？","delay_seconds":4,"variations":["关于那个项目，你有什么想法？","关于那个项目，你有什么想法？"]},{"role":"responder","message":"会议安排在明天可以吗？","delay_seconds":4,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"initiator","message":"保持联系！","delay_seconds":2,"variations":["保持联系！","保持联系！","保持联系！"]}]',
    '1.0.0',
    true,
    66,
    89,
    4.558806784665505,
    43,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '兴趣爱好分享 5',
    '分享兴趣爱好的对话',
    'hobby',
    'acquaintances',
    'evening',
    12,
    'easy',
    ARRAY['兴趣', '爱好', '分享'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":5,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？","哈喽啊！这段时间如何？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":4,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":3,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"很高兴和你聊天","delay_seconds":2,"variations":["很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    7,
    97,
    4.362898719825963,
    39,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '健身话题讨论 5',
    '讨论健身和健康的对话',
    'hobby',
    'friends',
    'any',
    10,
    'medium',
    ARRAY['健身', '健康', '运动'],
    '[{"role":"initiator","message":"你好！最近怎么样？","delay_seconds":3,"variations":["嗨！近来如何？","你好啊！这些天好吗？"]},{"role":"responder","message":"有什么好书推荐吗？","delay_seconds":3,"variations":["有什么好书推荐吗？","有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"initiator","message":"你喜欢什么类型的音乐？","delay_seconds":2,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":2,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"最近在玩什么游戏？","delay_seconds":5,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？","这段时间在玩什么游戏？"]},{"role":"responder","message":"你喜欢什么类型的音乐？","delay_seconds":5,"variations":["你喜欢什么类型的音乐？","你喜欢什么类型的音乐？","你喜欢什么类型的音乐？"]},{"role":"initiator","message":"好的，下次再聊","delay_seconds":3,"variations":["好的，下次再聊","好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    11,
    73,
    4.598200032652206,
    16,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '美食推荐 5',
    '推荐美食和餐厅的对话',
    'casual',
    'friends',
    'any',
    9,
    'easy',
    ARRAY['美食', '餐厅', '推荐'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":5,"variations":["嗨，近来如何？","嗨，这些天好吗？","嗨，这段时间怎样？"]},{"role":"responder","message":"周末有什么计划？","delay_seconds":3,"variations":["周末有什么计划？","周末有什么计划？","周末有什么计划？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":5,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":5,"variations":["近来工作忙吗？","这些天工作忙吗？","这段时间工作忙吗？"]},{"role":"initiator","message":"最近看了什么好电影？","delay_seconds":3,"variations":["近来看了什么好电影？","这些天看了什么好电影？"]},{"role":"responder","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错","今天天气不错"]},{"role":"initiator","message":"再见，祝你愉快","delay_seconds":4,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    89,
    90,
    3.6400877258174518,
    35,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '旅行计划 5',
    '讨论旅行计划的对话',
    'hobby',
    'friends',
    'any',
    12,
    'medium',
    ARRAY['旅行', '计划', '假期'],
    '[{"role":"initiator","message":"你好啊！最近如何？","delay_seconds":3,"variations":["嗨啊！近来如何？","你好啊啊！这些天如何？","哈喽啊！这段时间如何？"]},{"role":"responder","message":"你平时有什么兴趣爱好？","delay_seconds":2,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"initiator","message":"最近在玩什么游戏？","delay_seconds":2,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？","这段时间在玩什么游戏？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":2,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"initiator","message":"有什么好书推荐吗？","delay_seconds":4,"variations":["有什么好书推荐吗？","有什么好书推荐吗？"]},{"role":"responder","message":"再见，祝你愉快","delay_seconds":4,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    6,
    87,
    4.673707708873714,
    25,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '电影讨论 5',
    '讨论电影和影评的对话',
    'hobby',
    'acquaintances',
    'evening',
    11,
    'easy',
    ARRAY['电影', '娱乐', '讨论'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":2,"variations":["嗨！近来好吗？","嗨！这些天好吗？"]},{"role":"responder","message":"最近在玩什么游戏？","delay_seconds":2,"variations":["近来在玩什么游戏？","这些天在玩什么游戏？"]},{"role":"initiator","message":"你平时有什么兴趣爱好？","delay_seconds":3,"variations":["你平时有什么兴趣爱好？","你平时有什么兴趣爱好？","你平时有什么兴趣爱好？"]},{"role":"responder","message":"好的，下次再聊","delay_seconds":5,"variations":["好的，下次再聊","好的，下次再聊"]}]',
    '1.0.0',
    true,
    43,
    85,
    3.953743888221089,
    15,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '技术问题讨论 5',
    '讨论技术问题和解决方案的对话',
    'business',
    'colleagues',
    'any',
    15,
    'hard',
    ARRAY['技术', '问题', '解决方案'],
    '[{"role":"initiator","message":"嗨！最近好吗？","delay_seconds":4,"variations":["嗨！近来好吗？","嗨！这些天好吗？","嗨！这段时间好吗？"]},{"role":"responder","message":"会议安排在明天可以吗？","delay_seconds":5,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"initiator","message":"我们需要讨论一下进度","delay_seconds":5,"variations":["我们需要讨论一下进度","我们需要讨论一下进度"]},{"role":"responder","message":"会议安排在明天可以吗？","delay_seconds":4,"variations":["会议安排在明天可以吗？","会议安排在明天可以吗？"]},{"role":"initiator","message":"再见，祝你愉快","delay_seconds":5,"variations":["再见，祝你愉快","再见，祝你愉快","再见，祝你愉快"]}]',
    '1.0.0',
    true,
    59,
    95,
    4.284750836926023,
    35,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  ),
  (
    '天气话题 5',
    '讨论天气和季节变化的对话',
    'casual',
    'acquaintances',
    'any',
    6,
    'easy',
    ARRAY['天气', '季节', '日常'],
    '[{"role":"initiator","message":"嗨，最近怎么样？","delay_seconds":2,"variations":["嗨，近来如何？","嗨，这些天好吗？"]},{"role":"responder","message":"最近工作忙吗？","delay_seconds":3,"variations":["近来工作忙吗？","这些天工作忙吗？"]},{"role":"initiator","message":"今天天气不错","delay_seconds":3,"variations":["今天天气不错","今天天气不错"]},{"role":"responder","message":"周末有什么计划？","delay_seconds":3,"variations":["周末有什么计划？","周末有什么计划？"]},{"role":"initiator","message":"很高兴和你聊天","delay_seconds":3,"variations":["很高兴和你聊天","很高兴和你聊天","很高兴和你聊天"]}]',
    '1.0.0',
    true,
    85,
    87,
    4.06507763212847,
    3,
    '2026-04-12T10:15:31.398Z',
    '2026-04-12T10:15:31.398Z'
  );
